name: Robot Rekap Harian

on:
  schedule:
    # Berjalan otomatis setiap jam 08:00 WIB (01:00 UTC)
    - cron: '0 1 * * *'
  workflow_dispatch: # Tombol untuk menjalankan manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode dari GitHub
        uses: actions/checkout@v3

      - name: Siapkan Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instal Alat Pencapit
        run: pip install google_play_scraper requests

      - name: Jalankan Robot Rekap
        # DI SINI PERUBAHANNYA: Menghubungkan Brankas GitHub ke Python
        env:
          URL_GOOGLE_SHEETS: ${{ secrets.URL_GOOGLE_SHEETS }}
        run: python main.py
